DROP TABLE IF EXISTS "StAccount" CASCADE;
DROP TABLE IF EXISTS "TAccount" CASCADE;
DROP TABLE IF EXISTS "Auth" CASCADE;
DROP TABLE IF EXISTS "PlanRecord" CASCADE;
DROP TABLE IF EXISTS "PlanDesc" CASCADE;
DROP TABLE IF EXISTS "ClassRecord" CASCADE;
